<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Google Classroom 3.0</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
            background-color: #f0f0f0;
            min-height: 100vh; /* Ensures body takes full height */
            display: flex;
            justify-content: center;
            align-items: center; /* Centers container vertically */
        }
        .container {
            max-width: 800px;
            text-align: center;
        }
        h1 {
            color: #4285f4;
            margin-bottom: 20px; /* Adds spacing below title */
        }
        .browser-buttons {
            margin: 20px 0;
        }
        button {
            padding: 10px 20px;
            margin: 5px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            background-color: #4285f4;
            color: white;
            font-size: 16px;
            transition: background-color 0.3s ease; /* Smooth hover effect */
        }
        button:hover {
            background-color: #3267d6;
        }
        .browser-image {
            max-width: 100%; /* Responsive width */
            width: 500px; /* Default width */
            margin-top: 20px;
            display: none;
            border-radius: 5px; /* Matches button style */
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Google Classroom 3.0</h1>
        <div class="browser-buttons">
            <button onclick="showBrowser('chrome')">Chrome</button>
            <button onclick="showBrowser('firefox')">Firefox</button>
            <button onclick="showBrowser('edge')">Edge</button>
            <button onclick="showBrowser('safari')">Safari</button>
        </div>
        <img id="chrome-img" class="browser-image" src="https://via.placeholder.com/500x300?text=Chrome+Browser" alt="Chrome Browser">
        <img id="firefox-img" class="browser-image" src="https://via.placeholder.com/500x300?text=Firefox+Browser" alt="Firefox Browser">
        <img id="edge-img" class="browser-image" src="https://via.placeholder.com/500x300?text=Edge+Browser" alt="Edge Browser">
        <img id="safari-img" class="browser-image" src="https://via.placeholder.com/500x300?text=Safari+Browser" alt="Safari Browser">
    </div>

    <script>
        function showBrowser(browser) {
            // Hide all images
            const images = document.querySelectorAll('.browser-image');
            images.forEach(img => img.style.display = 'none');

            // Show selected browser image
            const selectedImg = document.getElementById(`${browser}-img`);
            if (selectedImg) {
                selectedImg.style.display = 'block';
            }

            // Change tab title based on browser
            const titles = {
                chrome: 'Google Chrome',
                firefox: 'Mozilla Firefox',
                edge: 'Microsoft Edge',
                safari: 'Apple Safari'
            };
            document.title = titles[browser] || 'Google Classroom 3.0';
        }

        // Show Chrome by default when page loads
        window.addEventListener('load', () => showBrowser('chrome'));
    </script>
</body>
</html>
